### PR TITLE
Correctly deallocate external typed data

### LINKED ISSUE #61: Panic in Vec::from_raw_parts on Android (arm64-v8a ABI)
Hi,

Thanks for the library! I am running into an issue with a Flutter app that uses `flutter_rust_bridge` and therefore `allo-isolate`.

The app compiles and works fine across Windows, Linux, MacOS, iOS and until recently Android.

For some reason (I don't know the underlying cause of why this has started) I am getting a SIGABRT crash on Android that looks like this (on a Samsung A325F physical device):

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a32xx/a32:13/TP1A.220624.014/A325FXXU2CVK3:user/release-keys'
Revision: '4'
ABI: 'arm64'
Processor: '4'
Timestamp: 2024-10-21 13:40:58.415385646+0800
Process uptime: 6s
Cmdline: com.app_id
pid: 12252, tid: 12329, name: DartWorker  >>> com.app_id <<<
uid: 10050
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  0000000000003029  x2  0000000000000006  x3  0000007a22d78a70
    x4  4341425f54535552  x5  4341425f54535552  x6  4341425f54535552  x7  45434152544b4341
    x8  00000000000000f0  x9  0000007b6a4f8b70  x10 0000000000000001  x11 0000007b6a56eab0
    x12 0000007a22d78789  x13 0000007a369ed000  x14 fffffffffc000000  x15 0000000000000010
    x16 0000007b6a5dfa48  x17 0000007b6a5b7c10  x18 0000007a22312000  x19 00000000000000ac
    x20 00000000000000b2  x21 0000000000002fdc  x22 0000000000003029  x23 00000000ffffffff
    x24 0000007a32d26b38  x25 0000000000000002  x26 0000000000000001  x27 0000000000000001
    x28 0000000000000470  x29 0000007a22d78af0
    lr  0000007b6a55ed84  sp  0000007a22d78a50  pc  0000007b6a55edb4  pst 0000000000001000
backtrace:
      #00 pc 000000000008ddb4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) (BuildId: b28657aea79cef158849a8bf4d77df55)
      #01 pc 0000000002c86f4c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #02 pc 0000000002c819f8  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #03 pc 0000000002c8164c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #04 pc 0000000002c7fd14  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #05 pc 0000000002c81344  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #06 pc 0000000002ca3a9c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #07 pc 0000000002ca3b14  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #08 pc 0000000002c119c0  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #09 pc 0000000002c127a4  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #10 pc 0000000002c12644  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #11 pc 0000000002c13124  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #12 pc 0000000002c11734  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #13 pc 0000000002c11708  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #14 pc 0000000002c0ea64  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk
      #15 pc 0000000002c0dcfc  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk (free_zero_copy_buffer_u8+64)
      #16 pc 0000000002517a58  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #17 pc 00000000022200a0  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #18 pc 000000000236973c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #19 pc 000000000236b49c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #20 pc 000000000236bae0  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #21 pc 000000000236aa58  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #22 pc 000000000236a6ac  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #23 pc 0000000002358354  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #24 pc 00000000023571c4  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #25 pc 000000000225d2c8  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #26 pc 0000000002296d68  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #27 pc 0000000002296cd0  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #28 pc 0000000002473eac  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #29 pc 00000000024745d0  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #30 pc 00000000024536f0  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #31 pc 000000000245aac4  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #32 pc 0000000002458258  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #33 pc 00000000024510a8  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #34 pc 00000000024516b0  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #35 pc 0000000002451a98  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #36 pc 000000000246195c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #37 pc 00000000023f9088  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #38 pc 00000000023f5568  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #39 pc 00000000023fb6ec  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #40 pc 00000000023f833c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #41 pc 00000000023f8074  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #42 pc 000000000243b0d8  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #43 pc 000000000243ab18  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #44 pc 000000000243ae1c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #45 pc 0000000002347e88  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #46 pc 0000000002348698  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #47 pc 0000000002348d48  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #48 pc 0000000002349270  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #49 pc 000000000233781c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #50 pc 0000000002337a6c  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #51 pc 00000000022ca1fc  /data/app/~~l4cqODr94fnjJEHnWBnXpw==/com.app_id-nEct2_NNOUKf9wOZcT16-Q==/base.apk!libflutter.so (BuildId: 401fddf00828b4e4366640aa543d24715c00b6bd)
      #52 pc 00000000000fd040  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: b28657aea79cef158849a8bf4d77df55)
      #53 pc 000000000008f5e0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: b28657aea79cef158849a8bf4d77df55)
```

Notice the `free_zero_copy_buffer_u8+64` indicating that this is coming from the `allo-isolate` code.

I checked that the crash does not happen if I comment out [this line](https://github.com/shekohex/allo-isolate/blob/master/src/into_dart.rs#L261) which makes me think that it is the `Vec::from_raw_parts` call that panics and is causing the abort.

It's possible that `flutter_rust_bridge` is creating the `Vec` in such a way that it breaks one of the [invariants](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.from_raw_parts).

I wonder if you could help me figure out the correct fix for this problem, thanks 🙏 

/cc @fzyzcjy

### PR DESCRIPTION
**Pull request by vlad9486**
This works well.

Closes #61

### CODE REVIEW

**Comment by vlad9486** [comment]
I tried running the same CI action on the master branch and vargrind fails there too. It is not my commit.

**Comment by vlad9486** [comment]
Please, try run CI again

image

**Comment by shekohex** [comment]
It looks like this issue happens when using rust nightly, on rust stable it works fine.
The CI is using nightly rust for testing, for some reason. 

Let me change the CI to work with stable rust instead.

File: src/into_dart.rs [hunk 1]
```diff
@@ -253,12 +257,12 @@ macro_rules! dart_typed_data_type_trait_impl {
...
-                isolate_callback_data: *mut c_void,
+                _isolate_callback_data: *mut c_void,
                 peer: *mut c_void,
             ) {
-                let len = (isolate_callback_data as isize) as usize;
-                let ptr = peer as *mut $rust_type;
-                drop(Vec::from_raw_parts(ptr, len, len));
+                let raw_slice = Box::from_raw(peer.cast::<*mut [u8]>());
+                let len = raw_slice.len();
+                drop(Vec::from_raw_parts(raw_slice.cast::<u8>(), len, len));
```
Comment (fzyzcjy) [inline src/into_dart.rs:265]: nit: are we guaranteed to have `u8` here (e.g. maybe it can be a `Vec<i32>` in the macro call)

File: src/into_dart.rs [hunk 2]
```diff
@@ -253,12 +257,12 @@ macro_rules! dart_typed_data_type_trait_impl {
             #[doc(hidden)]
             #[no_mangle]
             pub(crate) unsafe extern "C" fn $free_zero_copy_buffer_func(
-                isolate_callback_data: *mut c_void,
+                _isolate_callback_data: *mut c_void,
```
Comment (fzyzcjy) [inline src/into_dart.rs:260]: btw, curious why we cannot use isolate_callback_data today while we could before - has something changed in Dart/Rust?

File: src/into_dart.rs [hunk 3]
```diff
@@ -184,14 +184,18 @@ where
     assert_eq!(length, vec.capacity());
     let ptr = vec.as_mut_ptr();
 
+    let raw_slice = Box::into_raw(Box::new(
+        std::ptr::slice_from_raw_parts_mut(ptr, length),
+    ));
```
Comment (fzyzcjy) [inline src/into_dart.rs:189]: nit: `slice` has the semantics of (something similar to) "a borrowed vec", i.e. some lifetime things, thus maybe confuse the reader a little bit. Thus is the following alternative possible:

```rust
struct VecInfo { ptr, len }
let raw_info = Box::into_raw(Box::new(VecInfo { ptr, length }));
```

and recover it

```rust
let raw_info = Box::from_raw(peer);
Vec::from_raw_parts(raw_info.ptr, raw_info.len, raw_info.len)
```

**Review by fzyzcjy — COMMENTED** [review]
Just some tiny nits when glancing, you can ignore it if needed!

File: src/into_dart.rs (hunk 1 above)
Comment (vlad9486) [reply src/into_dart.rs:265]: Yes, you are right, this is mistake, I'll fix it.

File: src/into_dart.rs (hunk 2 above)
Comment (vlad9486) [reply src/into_dart.rs:260]: For some reason it still crashes when I use it instead of the original ptr. So I decided to put the ptr and length in the Box.

File: src/into_dart.rs (hunk 3 above)
Comment (vlad9486) [reply src/into_dart.rs:189]: This is so called raw slice, it is `*mut [u8]` has no lifetime. I just needed a structure to deliver both ptr and length, I could have created one, but I used what was already there.

Comment (fzyzcjy) [reply src/into_dart.rs]: You are right!

Comment (vlad9486) [reply src/into_dart.rs]: @fzyzcjy Please take a look again. I just figure out the simplest solution.

File: src/into_dart.rs [hunk 4]
```diff
@@ -178,20 +178,22 @@ where
...
     }
 
-    let mut vec = ManuallyDrop::new(vec_from_rust);
+    let mut vec = vec_from_rust;
     vec.shrink_to_fit();
     let length = vec.len();
     assert_eq!(length, vec.capacity());
     let ptr = vec.as_mut_ptr();
 
+    let raw_slice = Box::into_raw(Box::new(vec));
```
Comment (fzyzcjy) [inline src/into_dart.rs:187]: nit: it is a boxed vec instead of a slice now, so maybe the name can be updated

Comment (fzyzcjy) [reply src/into_dart.rs]: Ignore this one - I see the updated code :)

**Review by shekohex — APPROVED** [review]
LGTM!
